"fix to 7.0"

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,12 +28,15 @@ jobs:
           USER: ubuntu
         run: |
           # Crear archivo temporal para la clave privada con formato correcto
-          echo "$PRIVATE_KEY" | tr -d '\r' > private_key.pem
+          echo "$PRIVATE_KEY" | sed 's/\\n/\n/g' > private_key.pem
           chmod 600 private_key.pem
 
           # Agregar la clave al agente SSH
           eval "$(ssh-agent -s)"
           ssh-add private_key.pem
+
+          # Probar la clave antes de usarla
+          ssh-keygen -y -f private_key.pem || { echo "❌ Error en la clave privada"; exit 1; }
 
           # Conectarse a EC2 y ejecutar comandos
           ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
